// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiSigSchnorr.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiSigSchnorr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MultiSigSchnorrDbContext))]
    [Migration("20260425123319_AddProtocolSessionProjection")]
    partial class AddProtocolSessionProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.AuditLogEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_utc");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("epochs", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_utc");

                    b.Property<Guid>("EpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("epoch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTime?>("RemovedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_utc");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("EpochId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("epoch_members", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("PublicKeyHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_hex");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ProtocolSessionParticipantProjectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregationCoefficientHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregation_coefficient_hex");

                    b.Property<string>("CommitmentHex")
                        .HasColumnType("text")
                        .HasColumnName("commitment_hex");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("HasCommitment")
                        .HasColumnType("boolean")
                        .HasColumnName("has_commitment");

                    b.Property<bool>("HasPartialSignature")
                        .HasColumnType("boolean")
                        .HasColumnName("has_partial_signature");

                    b.Property<bool>("HasReveal")
                        .HasColumnType("boolean")
                        .HasColumnName("has_reveal");

                    b.Property<string>("PartialSignatureHex")
                        .HasColumnType("text")
                        .HasColumnName("partial_signature_hex");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<string>("PublicKeyHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_hex");

                    b.Property<string>("PublicNoncePointHex")
                        .HasColumnType("text")
                        .HasColumnName("public_nonce_point_hex");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("protocol_session_participants", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ProtocolSessionProjectionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("AggregateNoncePointHex")
                        .HasColumnType("text")
                        .HasColumnName("aggregate_nonce_point_hex");

                    b.Property<string>("AggregatePublicKeyHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_public_key_hex");

                    b.Property<string>("AggregateSignatureNoncePointHex")
                        .HasColumnType("text")
                        .HasColumnName("aggregate_signature_nonce_point_hex");

                    b.Property<string>("AggregateSignatureScalarHex")
                        .HasColumnType("text")
                        .HasColumnName("aggregate_signature_scalar_hex");

                    b.Property<bool>("AllCommitmentsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("all_commitments_published");

                    b.Property<bool>("AllNoncesRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("all_nonces_revealed");

                    b.Property<bool>("AllPartialSignaturesSubmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("all_partial_signatures_submitted");

                    b.Property<string>("ChallengeHex")
                        .HasColumnType("text")
                        .HasColumnName("challenge_hex");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("EpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("epoch_id");

                    b.Property<int>("EpochNumber")
                        .HasColumnType("integer")
                        .HasColumnName("epoch_number");

                    b.Property<string>("MessageDigestHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_digest_hex");

                    b.Property<string>("ProtectionMode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("protection_mode");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_status");

                    b.HasKey("SessionId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EpochId");

                    b.HasIndex("ProtectionMode");

                    b.HasIndex("SessionStatus");

                    b.ToTable("protocol_sessions", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochMemberEntity", b =>
                {
                    b.HasOne("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochEntity", null)
                        .WithMany()
                        .HasForeignKey("EpochId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultiSigSchnorr.Infrastructure.Persistence.Entities.ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ProtocolSessionParticipantProjectionEntity", b =>
                {
                    b.HasOne("MultiSigSchnorr.Infrastructure.Persistence.Entities.ProtocolSessionProjectionEntity", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ProtocolSessionProjectionEntity", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
