// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiSigSchnorr.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultiSigSchnorr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MultiSigSchnorrDbContext))]
    partial class MultiSigSchnorrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.AuditLogEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_utc");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("epochs", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_utc");

                    b.Property<Guid>("EpochId")
                        .HasColumnType("uuid")
                        .HasColumnName("epoch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTime?>("RemovedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_utc");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("EpochId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("epoch_members", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("PublicKeyHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key_hex");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochMemberEntity", b =>
                {
                    b.HasOne("MultiSigSchnorr.Infrastructure.Persistence.Entities.EpochEntity", null)
                        .WithMany()
                        .HasForeignKey("EpochId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultiSigSchnorr.Infrastructure.Persistence.Entities.ParticipantEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
